language: python
cache: pip
sudo: false

os:
  - linux
  - osx

matrix:
  include:
    - python: "2.7"
      env: DEPS="numpy scipy astropy=1.1" 
    - python: "2.7"
      env: DEPS="numpy scipy astropy=1.2" COVERAGE=true
    - python: "3.4"
      env: DEPS="numpy scipy astropy=1.1"
    - python: "3.4"
      env: DEPS="numpy scipy astropy=1.2"
    - python: "3.5"
      env: DEPS="numpy scipy astropy=1.1"
    - python: "3.5"
      env: DEPS="numpy scipy astropy=1.2"

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  # See:
  # https://groups.google.com/a/continuum.io/forum/#!topic/conda/RSFENqovnro
  # - conda update --yes --no-deps conda
  # OK, this used to *fix* the build, but now it *breaks* the build.
  # If you're reading this, good luck out there. I'm not sure what to tell you.
  - conda update --yes conda
  - conda create -n testenv --yes $DEPS pip pytest setuptools Cython six>=1.7 pyyaml matplotlib python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  # for debugging...
  - conda list
  - if [[ $COVERAGE == true ]]; then pip install codeclimate-test-reporter; fi
  - if [[ $COVERAGE == true ]]; then pip install coveralls; fi
  - pip list
  # Build in place so we can run tests
  - python setup.py build_ext --inplace

script: 
  - py.test numina
  - if [[ $COVERAGE == true ]]; then coverage run --source numina -m py.test; fi
after_success:
  - if [[ $COVERAGE == true ]]; then coveralls; fi
  - if [[ $COVERAGE == true ]]; then codeclimate-test-reporter; fi

